apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ticketing
resources:
- ../../base
images:
- name: ghcr.io/monashautomation/ticketing-bot
  newTag: sha-0c84c04
- name: ghcr.io/monashautomation/ticketing-migrate
  newTag: sha-0c84c04
- name: ghcr.io/monashautomation/ticketing-web
  newTag: sha-0c84c04
replicas:
- count: 2
  name: ticketing-web
