apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticketing-web
spec:
  selector:
    matchLabels:
      app: ticketing-web
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
